#Exploratory Functions

In [1]:
# Data Frame Exploration 

def explore_df(Data_Frame):
  ### This function finds exploratory information on the DataFrame, and Returns a Summary ###
    # Explore
  Data_Frame_head = Data_Frame.head()
  Data_Frame_shape = Data_Frame.shape
  Data_Frame_nulls = Data_Frame.isnull().sum()
  Data_Frame_null_sum = Data_Frame.isnull().sum().sum()
  Data_Frame_desc = Data_Frame.describe()
  Data_Frame_info = Data_Frame.info()
    #Summary
  print(f'''

  
Text Data Frame Exploration Values

Shape: {Data_Frame_shape}

Total Null Values: {Data_Frame_null_sum}
Null Distribution:
{Data_Frame_nulls}

Data Statistical Summary:
{Data_Frame_desc}
''')
  return Data_Frame_head

In [2]:
# Column Exploration

def col_info(col):
  ### This function returns column information ###
  col_total = col.value_counts().sum()
  col_Val_count = col.value_counts()
  col_freq = col.value_counts(normalize=True)*100
  col_unique = col.nunique()

  print(f"""
There are {col_total} samples in {col_unique} cateogries.
  
Sample Count per Category:
{col_Val_count}

Sample Frequency per Category:
{col_freq}
  """)

#Examining the available Data Sets

[Data Set Source](https://mushroom.mathematik.uni-marburg.de/)



1.   Primary Data Set
2.   Secondary Data Set Generated
3.   Secondary Data Set No Missing Values

In [3]:
import pandas as pd

In [4]:
#Primary

  #Data Set
df1_url ='https://raw.githubusercontent.com/CelinaWalkowicz/Mushroom_Analysis/main/primary_data_generated.csv'
df1 = pd.read_csv(df1_url, delimiter=";")

explore_df(df1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   family                0 non-null      float64
 1   name                  236 non-null    object
 2   class                 236 non-null    object
 3   cap-diameter          236 non-null    object
 4   cap-shape             119 non-null    object
 5   cap-surface           100 non-null    object
 6   cap-color             122 non-null    object
 7   does-bruise-or-bleed  236 non-null    object
 8   gill-attachment       119 non-null    object
 9   gill-spacing          75 non-null     object
 10  gill-color            115 non-null    object
 11  stem-height           236 non-null    object
 12  stem-width            236 non-null    object
 13  stem-root             9 non-null      object
 14  stem-surface          63 non-null     object
 15  stem-color            110 non-null    object
 16  veil-type             1 non-null      object
 17  veil-color            16 non-null     object
 18  has-ring              236 non-null    object
 19  ring-type             236 non-null    object
 20  spore-print-color     23 non-null     object
 21  habitat               184 non-null    object
 22  season                207 non-null    object
dtypes: float64(1), object(22)
memory usage: 42.5+ KB



Text Data Frame Exploration Values

Shape: (236, 23)

Total Null Values: 2277
Null Distribution:
family                  236
name                      0
class                     0
cap-diameter              0
cap-shape               117
cap-surface             136
cap-color               114
does-bruise-or-bleed      0
gill-attachment         117
gill-spacing            161
gill-color              121
stem-height               0
stem-width                0
stem-root               227
stem-surface            173
stem-color              126
veil-type               235
veil-color              220
has-ring                  0
ring-type                 0
spore-print-color       213
habitat                  52
season                   29
dtype: int64

Data Statistical Summary:
       family
count     0.0
mean      NaN
std       NaN
min       NaN
25%       NaN
50%       NaN
75%       NaN
max       NaN

   family               name class  ... spore-print-color habitat  season
0     NaN         Fly Agaric     p  ...               NaN     NaN  [u, w]
1     NaN        Panther Cap     p  ...               NaN  [l, d]  [u, a]
2     NaN  False Panther Cap     p  ...               NaN  [l, d]  [u, a]
3     NaN        The Blusher     e  ...               NaN  [l, d]  [u, a]
4     NaN          Death Cap     p  ...               NaN  [l, d]  [u, a]

[5 rows x 23 columns]

In [5]:
# Secondary Gen

  #Data Set
df2_url = 'https://raw.githubusercontent.com/CelinaWalkowicz/Mushroom_Analysis/main/secondary_data_generated.csv'
df2 = pd.read_csv(df2_url, delimiter=";")

explore_df(df2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           46949 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       51185 non-null  object
 7   gill-spacing          36006 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-root             9531 non-null   object
 12  stem-surface          22945 non-null  object
 13  stem-color            61069 non-null  object
 14  veil-type             3177 non-null   object
 15  veil-color            7413 non-null   object
 16  has-ring              61069 non-null  object
 17  ring-type             58598 non-null  object
 18  spore-print-color     6354 non-null   object
 19  habitat               61069 non-null  object
 20  season                61069 non-null  object
dtypes: float64(3), object(18)
memory usage: 9.8+ MB



Text Data Frame Exploration Values

Shape: (61069, 21)

Total Null Values: 307463
Null Distribution:
class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

Data Statistical Summary:
       cap-diameter   stem-height    stem-width
count  61069.000000  61069.000000  61069.000000
mean       6.733854      6.581538     12.149410
std        5.264845      3.370017     10.035955
min        0.380000      0.000000      0.000000
25%        3.480000      4.640000      5.210000
50%        5.860000      5.950000     10.190000
75%        8.540000      7.740000     16.570000
max       62.340000     33.920000    103.910000

  class  cap-diameter cap-shape  ... spore-print-color habitat season
0     p         15.26         x  ...               NaN       d      w
1     p         16.60         x  ...               NaN       d      u
2     p         14.07         x  ...               NaN       d      w
3     p         14.17         f  ...               NaN       d      w
4     p         14.64         x  ...               NaN       d      w

[5 rows x 21 columns]

In [7]:
# Secondary Gen No Miss

  # Data Set
df3_url = 'https://raw.githubusercontent.com/CelinaWalkowicz/Mushroom_Analysis/main/secondary_data_no_miss.csv'
df3 = pd.read_csv(df3_url, delimiter=";")

explore_df(df3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           61069 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       61069 non-null  object
 7   gill-spacing          61069 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-color            61069 non-null  object
 12  has-ring              61069 non-null  object
 13  ring-type             61069 non-null  object
 14  habitat               61069 non-null  object
 15  season                61069 non-null  object
dtypes: float64(3), object(13)
memory usage: 7.5+ MB



Text Data Frame Exploration Values

Shape: (61069, 16)

Total Null Values: 0
Null Distribution:
class                   0
cap-diameter            0
cap-shape               0
cap-surface             0
cap-color               0
does-bruise-or-bleed    0
gill-attachment         0
gill-spacing            0
gill-color              0
stem-height             0
stem-width              0
stem-color              0
has-ring                0
ring-type               0
habitat                 0
season                  0
dtype: int64

Data Statistical Summary:
       cap-diameter   stem-height    stem-width
count  61069.000000  61069.000000  61069.000000
mean       6.746893      6.588775     12.155013
std        5.262972      3.362591      9.989620
min        0.410000      0.000000      0.000000
25%        3.490000      4.640000      5.200000
50%        5.890000      5.960000     10.180000
75%        8.540000      7.760000     16.600000
max       61.580000     35.790000    100.830000

  class  cap-diameter cap-shape cap-surface  ... has-ring ring-type habitat season
0     e          1.26         x           g  ...        f         f       d      a
1     e         10.32         f           e  ...        t         f       d      a
2     p          0.92         x           g  ...        f         f       d      u
3     p          4.27         x           t  ...        f         f       d      a
4     e          3.08         f           s  ...        f         f       m      a

[5 rows x 16 columns]

#Exploring Cap Colors

1.   Primary Data Set
2.   Secondary Data Set

In [9]:
# 1. Primary Data Set Cap Color Information 

col_info(df1['cap-color'])

There are 122 samples in 45 cateogries.

Sample Count per Category:
[n]             32
[y]              9
[n, y]           8
[n, e]           6
[n, w]           6
[w]              6
[n, o]           3
[o]              3
[n, p]           3
[l]              2
[r, l, w]        2
[w, y]           2
[y, n]           2
[n, p, e]        2
[n, k]           2
[y, o]           2
[e]              2
[n, o, n]        2
[b]              2
[n, r, y]        1
[n, p, e, y]     1
[y, n, e, y]     1
[n, b]           1
[k]              1
[n, w, w]        1
[n, n, y]        1
[b, p, e, y]     1
[r, p, y]        1
[k, n]           1
[n, e, o]        1
[n, e, y]        1
[n, n, y, o]     1
[n, o, y]        1
[r]              1
[n, n]           1
[n, e, y, o]     1
[n, r, y, l]     1
[p, e, o]        1
[l, k]           1
[n, r, u, y]     1
[p, u]           1
[p]              1
[u, y]           1
[p, w]           1
[n, w, k]        1
Name: cap-color, dtype: int64

Sample Frequency per Category:
[n]             26.229508
[y]              7.377049
[n, y]           6.557377
[n, e]           4.918033
[n, w]           4.918033
[w]              4.918033
[n, o]           2.459016
[o]              2.459016
[n, p]           2.459016
[l]              1.639344
[r, l, w]        1.639344
[w, y]           1.639344
[y, n]           1.639344
[n, p, e]        1.639344
[n, k]           1.639344
[y, o]           1.639344
[e]              1.639344
[n, o, n]        1.639344
[b]              1.639344
[n, r, y]        0.819672
[n, p, e, y]     0.819672
[y, n, e, y]     0.819672
[n, b]           0.819672
[k]              0.819672
[n, w, w]        0.819672
[n, n, y]        0.819672
[b, p, e, y]     0.819672
[r, p, y]        0.819672
[k, n]           0.819672
[n, e, o]        0.819672
[n, e, y]        0.819672
[n, n, y, o]     0.819672
[n, o, y]        0.819672
[r]              0.819672
[n, n]           0.819672
[n, e, y, o]     0.819672
[n, r, y, l]     0.819672
[p, e, o]        0.819672
[l, k]           0.819672
[n, r, u, y]     0.819672
[p, u]           0.819672
[p]              0.819672
[u, y]           0.819672
[p, w]           0.819672
[n, w, k]        0.819672
Name: cap-color, dtype: float64

In [11]:
# 2. Secondary Data Set

col_info(df2['cap-color'])

There are 61069 samples in 12 cateogries.

Sample Count per Category:
n    24218
y     8543
w     7666
g     4420
e     4035
o     3656
r     1782
u     1709
p     1703
k     1279
b     1230
l      828
Name: cap-color, dtype: int64

Sample Frequency per Category:
n    39.656782
y    13.989094
w    12.553014
g     7.237715
e     6.607280
o     5.986671
r     2.918011
u     2.798474
p     2.788649
k     2.094352
b     2.014115
l     1.355843
Name: cap-color, dtype: float64